export const TIME_ENTRY_TAGS = [
  "Daily Tasks",
  "Beeston Day",
  "Commenting",
  "DMs",
  "Posting",
  "Returns",
  "Snapchat",
  "Links",
  "Brainstorming",
  "Amazon Storefront",
  "YouTube",
  "Shorts",
  "LTK",
  "ShopMy",
  "Editing Video",
  "Meeting",
  "Briefs",
  "Analytics",
  "Donations",
  "Task Day",
  "Emails",
  "Cleaning",
];

export const REIMBURSEMENT_TAGS = [
  "Food/Lunch",
  "Coffee/Drinks",
  "Return Package",
  "Car Wash",
  "Lightroom",
  "Gas/Car Maintenance",
  "Giveaway Items",
  "Subscriptions",
  "Supplies",
  "Decorations",
  "Clothing/Merchandise",
];
